alter table product add bundle_name varchar(32);

UPDATE product set description='A/B Tester', bundle_name='ab_tester' where name='lsp-plugins-ab-tester';
UPDATE product set description='Artistic Delay', bundle_name='art_delay' where name='lsp-plugins-art-delay';
UPDATE product set description='Beat Breather', bundle_name='beat_breather' where name='lsp-plugins-beat-breather';
UPDATE product set description='Chorus', bundle_name='chorus' where name='lsp-plugins-chorus';
UPDATE product set description='Clipper', bundle_name='clipper' where name='lsp-plugins-clipper';
UPDATE product set description='Compensation Delay', bundle_name='comp_delay' where name='lsp-plugins-comp-delay';
UPDATE product set description='Filter', bundle_name='filter' where name='lsp-plugins-filter';
UPDATE product set description='Flanger', bundle_name='flanger' where name='lsp-plugins-flanger';
UPDATE product set description='Impulse Responses', bundle_name='impulse_responses' where name='lsp-plugins-impulse-responses';
UPDATE product set description='Impulse Reverb', bundle_name='impulse_reverb' where name='lsp-plugins-impulse-reverb';
UPDATE product set description='Latency Meter', bundle_name='latency_meter' where name='lsp-plugins-latency-meter';
UPDATE product set description='Loudness Compensator', bundle_name='loud_comp' where name='lsp-plugins-loud-comp';
UPDATE product set description='Multiband Clipper', bundle_name='mb_clipper' where name='lsp-plugins-mb-clipper';
UPDATE product set description='Mixer', bundle_name='mixer' where name='lsp-plugins-mixer';
UPDATE product set description='Noise Generator', bundle_name='noise_generator' where name='lsp-plugins-noise-generator';
UPDATE product set description='Oscillator', bundle_name='oscillator' where name='lsp-plugins-oscillator';
UPDATE product set description='Oscilloscope', bundle_name='oscilloscope' where name='lsp-plugins-oscilloscope';
UPDATE product set description='Phase Detector', bundle_name='phase_detector' where name='lsp-plugins-phase-detector';
UPDATE product set description='Profiler', bundle_name='profiler' where name='lsp-plugins-profiler';
UPDATE product set description='Slap-back Delay', bundle_name='slap_delay' where name='lsp-plugins-slap-delay';
UPDATE product set description='Spectrum Analyzer', bundle_name='spectrum_analyzer' where name='lsp-plugins-spectrum-analyzer';
UPDATE product set description='Surge Filter', bundle_name='surge_filter' where name='lsp-plugins-surge-filter';
