UPDATE product set description='A/B Tester' where name='lsp-plugins-ab-tester';
UPDATE product set description='Artistic Delay' where name='lsp-plugins-art-delay';
UPDATE product set description='Beat Breather' where name='lsp-plugins-beat-breather';
UPDATE product set description='Chorus' where name='lsp-plugins-chorus';
UPDATE product set description='Clipper' where name='lsp-plugins-clipper';
UPDATE product set description='Compensation Delay' where name='lsp-plugins-comp-delay';
UPDATE product set description='Filter' where name='lsp-plugins-filter';
UPDATE product set description='Flanger' where name='lsp-plugins-flanger';
UPDATE product set description='Impulse Responses' where name='lsp-plugins-impulse-responses';
UPDATE product set description='Impulse Reverb' where name='lsp-plugins-impulse-reverb';
UPDATE product set description='Latency Meter' where name='lsp-plugins-latency-meter';
UPDATE product set description='Loudness Compensator' where name='lsp-plugins-loud-comp';
UPDATE product set description='Multiband Clipper' where name='lsp-plugins-mb-clipper';
UPDATE product set description='Mixer' where name='lsp-plugins-mixer';
UPDATE product set description='Noise Generator' where name='lsp-plugins-noise-generator';
UPDATE product set description='Oscillator' where name='lsp-plugins-oscillator';
UPDATE product set description='Oscilloscope' where name='lsp-plugins-oscilloscope';
UPDATE product set description='Phase Detector' where name='lsp-plugins-phase-detector';
UPDATE product set description='Profiler' where name='lsp-plugins-profiler';
UPDATE product set description='Slap-back Delay' where name='lsp-plugins-slap-delay';
UPDATE product set description='Spectrum Analyzer' where name='lsp-plugins-spectrum-analyzer';
UPDATE product set description='Surge Filter' where name='lsp-plugins-surge-filter';
    